### ISSUE TITLE
[Bug] HOTFIX! Multiple commands produce Error

### ISSUE THREAD

**Issue by Gobans** [DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel#86]
# Bug note
> Step-by-step explanation of what situation occurred from the start to the bug

<img width="859" alt="image" src="https://user-images.githubusercontent.com/56781342/174426166-6668f0bb-7457-48b1-a843-f2521d1058ad.png">

Multiple commands produce Error is occured because of Equipment Group, Equipment both have "폴대"

## Expected result
> Write down the specific results that need to be corrected.

- Remove it

## References
> In the case of the view shown, a screenshot is also attached.

- https://zetal.tistory.com/entry/Multiple-commands-produce-Error-해결법

**Comment by mijinc** [comment]
Thanks, Goban for the alert!
Checked ✅
